---
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - git config --global user.name "Dist Zilla Plugin TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
  - cpanm  --quiet  --notest --skip-installed Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm  --quiet   --notest  --skip-installed
  - dzil listdeps | grep -ve '^\W' | cpanm  --quiet   --notest  --skip-installed
language: perl
matrix:
  include:
    - perl: '5.30'
    - perl: '5.28'
    - perl: '5.26'
    - perl: '5.24'
    - perl: '5.22'
    - dist: trusty
      perl: '5.20'
    - dist: trusty
      perl: '5.18'
    - dist: trusty
      perl: '5.16'
    - dist: trusty
      perl: '5.14'
script:
  - dzil smoke --release --author
