language: perl
perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
#   - 5.12
#   - 5.10
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps | cpanm --quiet --notest --skip-satisfied"
   - "dzil listdeps   | cpanm --quiet --notest --skip-satisfied"
script:
   - dzil smoke --release --author
